[envs.default]
installer = "uv"
dependency-groups = ["dev"]
features = ["pydantic"]

[envs.hatch-static-analysis]
dependencies = ["ruff==0.15.*"]
config-path = ".ruff_defaults.toml"

[envs.hatch-test]
features = ["pydantic"]

[envs.coverage]
skip-install = true

[envs.coverage.scripts]
combine = "coverage combine {args}"
xml = "coverage xml"

[envs.types]
features = ["pydantic"]
scripts = { check = "mypy {args:schwifty tests}" }

[envs.docs]
dependency-groups = ["doc"]
scripts = { check = "doc8 docs/source" }

