name: publish

on:
  push:
    tags: ["*"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@8
        with:
          python-version: "3.13"
      - name: Build
        run: uv build
      - name: Publish
        env:
          UV_PUBLISH_USERNAME: ${{ secrets.PYPI_USERNAME }}
          UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: uv publish
